version: '3'

services:
  dns:
    container_name: dns
    image: ubuntu/bind9:9.18-22.04_beta
    environment:
      - BIND9_USER=root
      - TZ=UTC
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/:/etc/bind

  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx:1.24.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy:/etc/nginx/conf.d

  test-server:
    container_name: test-server
    build: ./test-server
    ports:
      - "3000:3000"
